# Main github repository to fetch from.
# This is going to be our base, into which we merge patches and pull requests.
#
# Examples
# 
# repo = "helix-editor/helix"
# repo = "microsoft/vscode"

repo = "helix-editor/helix"

# The main repository's branch
# 
# Examples
#
# remote-branch = "master"
# remote-branch = "main"

remote-branch = "master"

# Branch which patchy will use to do all of its work on
#
# Examples
#
# local-branch = "some-branch-1234"

local-branch = "patchy"

# list of pull requests numbers which you would like to merge into the repository and branch you have specified previously
#
# Examples
#
# pull-requests = [ "12254", "10000", "8145"]

pull-requests = []

# Optional: A list of patches to apply
#
# A patch allows you to do specify custom commits and not have to rely on there being a pull request for that change
#
# You can generate patches from a commit with: `patchy gen-patch <commit-id>`. See `patchy --help` for more info.
#
# Examples
#
# With the below config, patchcy will look for the following files:
# - `.patchy/my-patch123.patch`
# - `.patchy/another-patch.patch`
# - `.patchy/1234.patch`
#
# patches = [ "my-patch123", "another-patch", "1234" ]

# patches = []
